apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonebook-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phonebook-mysql
  template:
    metadata:
      labels:
        app: phonebook-mysql
    spec:
      containers:
      - name: mysql
        image: oualid70/phonebook-mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "yourpassword"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
