FROM python:3.8-alpine

RUN apk add --no-cache gcc musl-dev libffi-dev
RUN pip install cryptography

WORKDIR /app
COPY source_code/ /app

RUN pip install -r requirements.txt

ENTRYPOINT ["python", "server.py"]
